name:                structured-text
version:             0.1.0.0
git:                 "https://code.ornl.gov/defcon-scada/structured-text"
# license:             BSD3
author:              "Chris Hathhorn et al."
maintainer:          "hathhorncr@ornl.gov"
copyright:           "2020 Oak Ridge National Laboratory"
synopsis:            "Tools for the IEC 61131-3 structured text (ST) language. See: https://en.wikipedia.org/wiki/IEC_61131-3."
category:            Development
description:         Please see the README.

extra-source-files:
- README.md
- ChangeLog.md
data-files:
- samples/*.st

dependencies:
- base >= 4.7 && < 5
- text >= 1.2.4 && < 1.2.5
- prettyprinter >= 1.7 && < 1.8

library:
  source-dirs: src
  dependencies:
  - attoparsec >= 0.13.2 && < 0.13.3

executables:
  st-parse:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - structured-text

tests:
  structured-text-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - structured-text
    - tasty >= 1.2 && < 1.3
    - tasty-hspec >= 1.1 && < 1.2
    - directory >= 1.3 && < 1.4
    - hspec-attoparsec >= 0.1 && < 0.2
    - filepath >= 1.4 && < 1.5
