name:                structured-text
version:             0.1.0.0
git:                 "https://code.ornl.gov/defcon-scada/structured-text"
# license:             BSD3
author:              "Chris Hathhorn et al."
maintainer:          "hathhorncr@ornl.gov"
copyright:           "2020 Oak Ridge National Laboratory"
synopsis:            Tools for the IEC 61131-3 structured text (ST) language. See: https://en.wikipedia.org/wiki/IEC_61131-3.
category:            Development

extra-source-files:
- README.md
- ChangeLog.md

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/structured-text#readme>

dependencies:
- base >= 4.7 && < 5
- text >= 1.2.4 && < 1.2.5
- prettyprinter >= 1.7 && < 1.8

library:
  source-dirs: src

executables:
  structured-text-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - structured-text

tests:
  structured-text-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - structured-text
